DROP DATABASE IF EXISTS CS401;
CREATE DATABASE CS401;
USE CS401;

CREATE TABLE Users(
userID int NOT NULL Primary key auto_increment ,
username VARCHAR(256) NOT NULL,
passwd VARCHAR(80) NOT NULL
);

CREATE TABLE Notes(
username VARCHAR(256) NOT NULL,
url VARCHAR(256) NOT NULL,
FOREIGN KEY (username) REFERENCES Users(username)
);

CREATE TABLE Feedback(
guest VARCHAR(256) NOT NULL ,
email VARCHAR(256) NOT NULL,
feedback VARCHAR(5000) NOT NULL
);
select * from Feedback;
SELECT * FROM Users;
